replicaCount: 1
image:
  repository: JSourabh/pipeline-deploy-argo
  pullPolicy: IfNotPresent
  tag: v1.2
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
